[package]
name = "willbanksy"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
shuttle-rocket = "0.47.0"
shuttle-runtime = "0.47.0"
tokio = "1.26.0"
rocket_dyn_templates = { version = "0.2.0", features = [ "tera" ] }
serde = "1.0.210"
serde_yml = "0.0.12"
